[[PPL]]
arch = "aarch64"
git-tree-sha1 = "37461d5d32ba8794a59c8ee39e7d06df156bc1ec"
os = "macos"

    [[PPL.download]]
    sha256 = "36bc50a6c896d9913be6da2e8a455bbe966a26a1c2d3fd3f7e81426c5d3bfaf6"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.1+0/PPL.v1.2.1.aarch64-apple-darwin.tar.gz"
[[PPL]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2662654d26899411e06450c33d318da092b5f0b0"
libc = "glibc"
os = "linux"

    [[PPL.download]]
    sha256 = "86eca111c4335c31519919c984f137892fab16a4e8e55f8b71be496c44d903c4"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.1+0/PPL.v1.2.1.aarch64-linux-gnu-cxx03.tar.gz"
[[PPL]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5c5c70f9ae626ed540617b5589620bc8a44410f5"
libc = "glibc"
os = "linux"

    [[PPL.download]]
    sha256 = "ba66e035046d100a507922dbe9f5ed896230bf97a3eeca66e6d6625564de7ab0"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.1+0/PPL.v1.2.1.aarch64-linux-gnu-cxx11.tar.gz"
[[PPL]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "62dd3e648f826a8ea0ca936b7991eac0f8f5d3c1"
libc = "musl"
os = "linux"

    [[PPL.download]]
    sha256 = "72f34da62afa065575df8d1564514acc84344ce92e03333e11d3270f8ba0dea8"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.1+0/PPL.v1.2.1.aarch64-linux-musl-cxx03.tar.gz"
[[PPL]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a7823e031af548c579a226655e89f70542f01ecc"
libc = "musl"
os = "linux"

    [[PPL.download]]
    sha256 = "f050eaa1c0e76e59509825909f24cf2dad2803606adfe131d7a4905ad4baf4f7"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.1+0/PPL.v1.2.1.aarch64-linux-musl-cxx11.tar.gz"
[[PPL]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c1f2ddd890238ce9caeb76831e56ed1fa19a7305"
libc = "glibc"
os = "linux"

    [[PPL.download]]
    sha256 = "bc317dd4622513248033b32aaab95d038c68481eee7a09ef26d3a1652d1b8454"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.1+0/PPL.v1.2.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[PPL]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1dc173538bf3323ac07032af9a55f2a15dc7fabe"
libc = "glibc"
os = "linux"

    [[PPL.download]]
    sha256 = "5f8214cbf819b22a1ded0b7ac22cea85cbc7f0ceaf3d99d0d7d3bff4fb218acf"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.1+0/PPL.v1.2.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[PPL]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "16f26c4111c48aa577c9503cafd151326ef3139c"
libc = "musl"
os = "linux"

    [[PPL.download]]
    sha256 = "6a69b002a8cc6686d55d696356bfc7b7c9ce2ff7520d788dbf0420343f726976"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.1+0/PPL.v1.2.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[PPL]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a22a8223f823f1bf9379d79122fc20a376579ec4"
libc = "musl"
os = "linux"

    [[PPL.download]]
    sha256 = "587dcfd335428d53ff13a29c796c1cf54206550f432d23da1766a2ea67b5832e"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.1+0/PPL.v1.2.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[PPL]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c705d8405108c8b3b76a98691f52a628a4b695fb"
libc = "glibc"
os = "linux"

    [[PPL.download]]
    sha256 = "914a57c759feb43435ee9405da5c831720e4888c920aa54269c8a164810abc12"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.1+0/PPL.v1.2.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[PPL]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eb0b7e51f4074d3c35561ccd91d93a847d067fcf"
libc = "glibc"
os = "linux"

    [[PPL.download]]
    sha256 = "0a85b9d01a8e31495596bdb724209f495efa65fbe42d0c20c5ca2513caac7e16"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.1+0/PPL.v1.2.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[PPL]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "90a6d1bab9fb2ccbdad4d18900aae3ef3f4109df"
libc = "musl"
os = "linux"

    [[PPL.download]]
    sha256 = "21b83d30d3d3d5546b0a004a34276158d652b9e886c5e01e60ca02e577349c11"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.1+0/PPL.v1.2.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[PPL]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a8a8b02ce38f583e68e6bafac0fc2a83ff14d2a0"
libc = "musl"
os = "linux"

    [[PPL.download]]
    sha256 = "cc4b1579f58018755b429828baeec6a84e36332a558fef52a18ec892c9939e3d"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.1+0/PPL.v1.2.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[PPL]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a97bad86f05c22ee7422061e133c4e0b2feba10b"
libc = "glibc"
os = "linux"

    [[PPL.download]]
    sha256 = "51431eff8d2343c3a0cde80b9c4d824a21269043fe2f85a3e1016ec1d743c458"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.1+0/PPL.v1.2.1.i686-linux-gnu-cxx03.tar.gz"
[[PPL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ee618e86019a4492a6e5efe68eb928135c9560c1"
libc = "glibc"
os = "linux"

    [[PPL.download]]
    sha256 = "b2e6435b47ff468701b34046ecd033104c19e129a1eed780e9f3b7093da0d485"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.1+0/PPL.v1.2.1.i686-linux-gnu-cxx11.tar.gz"
[[PPL]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aefb64babc235cb8a863b5667553b7294b8ad19a"
libc = "musl"
os = "linux"

    [[PPL.download]]
    sha256 = "b3274063ada209431462d2713edf4495dca18a05047d5027fa42dd59f188fc37"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.1+0/PPL.v1.2.1.i686-linux-musl-cxx03.tar.gz"
[[PPL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a2c31cdc41aa1f23436202737dc66d74d3066b9f"
libc = "musl"
os = "linux"

    [[PPL.download]]
    sha256 = "49e91bb7ba2882d2105ae6b5da23c9c35d81971da95c65341e7f3b0d71bca335"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.1+0/PPL.v1.2.1.i686-linux-musl-cxx11.tar.gz"
[[PPL]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c32d21a945d65a136431eb8208bb36991b906450"
os = "windows"

    [[PPL.download]]
    sha256 = "e7d4ba77b4f046836ba576b5bbd8c001104a274f6bca6403efef1df46eb9cc1d"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.1+0/PPL.v1.2.1.i686-w64-mingw32-cxx03.tar.gz"
[[PPL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fbaf92bfabc868c293c7a4594933b836c872286c"
os = "windows"

    [[PPL.download]]
    sha256 = "f17731ddb4e342aa288e1a1eb6cee433ec7da4c646d5bb3fdd9e460c723f0a60"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.1+0/PPL.v1.2.1.i686-w64-mingw32-cxx11.tar.gz"
[[PPL]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a22171d00b0356983bb39a4a4ac278ab47304abc"
libc = "glibc"
os = "linux"

    [[PPL.download]]
    sha256 = "5252741f441b2dcc78ee46f45bc9763885c181ca5daa052abd610d52a98304a8"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.1+0/PPL.v1.2.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[PPL]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a2564683175b4bfd56abe8d82d91b810c0e96aa9"
libc = "glibc"
os = "linux"

    [[PPL.download]]
    sha256 = "91c34069e0f01160091f9ab9abdedec72d71ffc46555bb5733c5683beb6a75fd"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.1+0/PPL.v1.2.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[PPL]]
arch = "x86_64"
git-tree-sha1 = "5ff821ffc87273950be5e528ded06562e2db2a30"
os = "macos"

    [[PPL.download]]
    sha256 = "54e9a6d56b9c4a80af566648cf239c802ad56941d560b97f3261bfde8053f927"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.1+0/PPL.v1.2.1.x86_64-apple-darwin.tar.gz"
[[PPL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "011f317a8f5380ed78e9d04141b7287db4892cb5"
libc = "glibc"
os = "linux"

    [[PPL.download]]
    sha256 = "e9b7f80659861c688f092d797a4ce0cea1cf9f0c0bf2d1dde40eabf23a13068a"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.1+0/PPL.v1.2.1.x86_64-linux-gnu-cxx03.tar.gz"
[[PPL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ab10e6b2374ffd2ae4e7068688a735886cef08ac"
libc = "glibc"
os = "linux"

    [[PPL.download]]
    sha256 = "7348b5465b099a3a7be0de12ff0ce5a1aa4a55b993c036f55850fae16a3be115"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.1+0/PPL.v1.2.1.x86_64-linux-gnu-cxx11.tar.gz"
[[PPL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a4eaf487186733550e4244bafa26d4f8497e3254"
libc = "musl"
os = "linux"

    [[PPL.download]]
    sha256 = "e5a27d9f22d19c033003429fcecaa54b663cd950c3c1a61695019247eb648633"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.1+0/PPL.v1.2.1.x86_64-linux-musl-cxx03.tar.gz"
[[PPL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1d463f8579d5efa819a8b4dfda804c4052e59740"
libc = "musl"
os = "linux"

    [[PPL.download]]
    sha256 = "4502fc691b6c674c470e65cd97b4f6b16b48d6002da610e08598b655cdeaaa9f"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.1+0/PPL.v1.2.1.x86_64-linux-musl-cxx11.tar.gz"
[[PPL]]
arch = "x86_64"
git-tree-sha1 = "089cf1c02bc972493ba9c4c6f9134cd8e2f4b3ad"
os = "freebsd"

    [[PPL.download]]
    sha256 = "cca516d5451a2965030b3d967b4b989c2f1dcc8070469223459cee8950c5631d"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.1+0/PPL.v1.2.1.x86_64-unknown-freebsd.tar.gz"
[[PPL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4c355a3d50dfefab80628631395b16fce5c53b4a"
os = "windows"

    [[PPL.download]]
    sha256 = "89cd64e6516f1acbc476f18d603f3be6a111df3a537cdf81fa38d57c9299289b"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.1+0/PPL.v1.2.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[PPL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cae8f53db094a8c7e71d7ec9d0703e90ae015e42"
os = "windows"

    [[PPL.download]]
    sha256 = "8e1b535c0e114dab385133f1506d16cea6393218e738728e75e7840e0c88d8d0"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.1+0/PPL.v1.2.1.x86_64-w64-mingw32-cxx11.tar.gz"
