[[PPL]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "656c1fe5859a38b5f697a7b109a7be1a264b6228"
libc = "glibc"
os = "linux"

    [[PPL.download]]
    sha256 = "e020f60e014501840222ffbf8358aeaaa53ccf77999e13454754095d570515f6"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.0+1/PPL.v1.2.0.aarch64-linux-gnu-cxx03.tar.gz"
[[PPL]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1920029c7c6602cb882d2e875b7c2fda83ec7772"
libc = "glibc"
os = "linux"

    [[PPL.download]]
    sha256 = "96a85303e72c391642196a29467025de8d7c681dfba2a6bcc006571412e6c03a"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.0+1/PPL.v1.2.0.aarch64-linux-gnu-cxx11.tar.gz"
[[PPL]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fc9b937d870cbfd2ed14625e7fb8fda7af07a7a1"
libc = "musl"
os = "linux"

    [[PPL.download]]
    sha256 = "d51d43136ec8ef734fab90caedd8e4cbe683aa23d9d199bbaa750a5757ad946c"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.0+1/PPL.v1.2.0.aarch64-linux-musl-cxx03.tar.gz"
[[PPL]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6b7da1fd67fb91d4fd1fdea559d945057922420a"
libc = "musl"
os = "linux"

    [[PPL.download]]
    sha256 = "de696474fbf38a5783a6347fb6bf2d747fe00d17bdbe22b7e0ade4136a8a16d5"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.0+1/PPL.v1.2.0.aarch64-linux-musl-cxx11.tar.gz"
[[PPL]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ddc0d36a8473c0ef9a2c5ea23f660bd3d60c8354"
libc = "glibc"
os = "linux"

    [[PPL.download]]
    sha256 = "b7894e64654bf94888855a1248b5137eb010c688027a52630a2ce8b8e5c5bef8"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.0+1/PPL.v1.2.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[PPL]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "122f86ba842dce1d18ebc9c584805a73c56b7de9"
libc = "glibc"
os = "linux"

    [[PPL.download]]
    sha256 = "7fa951e5f27b8d1fe119458585fdfd8d59c5e2150f40643fac72f6786c574402"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.0+1/PPL.v1.2.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[PPL]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "89ead612c54eccc0072dc98539acf300c2b21a68"
libc = "musl"
os = "linux"

    [[PPL.download]]
    sha256 = "08f569878a168f4e6c49379278dfad5d975c7a506879ea11b3a707cdeddf4a15"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.0+1/PPL.v1.2.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[PPL]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "645c554b2ac9ec581ca2c0dce7e7da5ee1f31323"
libc = "musl"
os = "linux"

    [[PPL.download]]
    sha256 = "fb9bf8015f1d60b57ba152fa4db2ec44fe9a4d0a68e840c49245119841b539e2"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.0+1/PPL.v1.2.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[PPL]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0b5768531ac5155c82c931d47fa52da20398ba3b"
libc = "glibc"
os = "linux"

    [[PPL.download]]
    sha256 = "8bbc15258a07fb51138a17feda44047776622fb1592e444993f7742efd3d53ba"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.0+1/PPL.v1.2.0.i686-linux-gnu-cxx03.tar.gz"
[[PPL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "347699ebf555d4804c5a122b91dc639e46436cc1"
libc = "glibc"
os = "linux"

    [[PPL.download]]
    sha256 = "008e7e54a036cee1e8ea621dd3bd265c7c93c7f3561a17370ce8dc7c372d0abb"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.0+1/PPL.v1.2.0.i686-linux-gnu-cxx11.tar.gz"
[[PPL]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ac0b8d50d5e52ce638b253c2e87facd0413efde4"
libc = "musl"
os = "linux"

    [[PPL.download]]
    sha256 = "9fec1e1b02a3c70ebfe3682b50f87eeaa6f3be37a232cdc5ba36b013cfe9d243"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.0+1/PPL.v1.2.0.i686-linux-musl-cxx03.tar.gz"
[[PPL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c3ff8da27241114b713fe8f0323cfe7e9670e154"
libc = "musl"
os = "linux"

    [[PPL.download]]
    sha256 = "f60b8a53fa610eb52682e385193969db0d4f65928245ef192b93ecaab2283449"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.0+1/PPL.v1.2.0.i686-linux-musl-cxx11.tar.gz"
[[PPL]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9bdb706a1e41841a187a5912d5f91458f9fe6a26"
os = "windows"

    [[PPL.download]]
    sha256 = "a5d9d03417944e6c192bdd17d63dcd51fbc02764d93d0013dd3c3a8a2a050275"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.0+1/PPL.v1.2.0.i686-w64-mingw32-cxx03.tar.gz"
[[PPL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ee22f911c5c117fe3f0587b93a1069b6566128b5"
os = "windows"

    [[PPL.download]]
    sha256 = "4bb037db9ff7ff3524d38a3e731240e93ecccbca2ed971fcb5be01d9cb974047"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.0+1/PPL.v1.2.0.i686-w64-mingw32-cxx11.tar.gz"
[[PPL]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b831852c778ff5b6bad6ada590d58ea44e46c798"
libc = "glibc"
os = "linux"

    [[PPL.download]]
    sha256 = "6abab3d685fc4ebf249f6fe71817ed0c8b70c87c57cd098c3ff3d385a890c005"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.0+1/PPL.v1.2.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[PPL]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ffa02b597c54f7a6516ba3b2fe9773c4c05abd42"
libc = "glibc"
os = "linux"

    [[PPL.download]]
    sha256 = "fd3d5583b2b99e9c7eecc171577bb848ff912fbe9e73076263c1ff1fc46fa4ca"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.0+1/PPL.v1.2.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[PPL]]
arch = "x86_64"
git-tree-sha1 = "9ed2a49f8990bdc4c4286f6c9719ad66e5ba08a4"
os = "macos"

    [[PPL.download]]
    sha256 = "9205c24f9984bae0d12c0720a60d0842533887385035022faacedc5c71ded142"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.0+1/PPL.v1.2.0.x86_64-apple-darwin.tar.gz"
[[PPL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "543879eee2dc9aef83685e343145c85493fb3dff"
libc = "glibc"
os = "linux"

    [[PPL.download]]
    sha256 = "ff86f8eb62de5a7811abc96ce76e2890e7aa592933ba2a85488371773daeb3e6"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.0+1/PPL.v1.2.0.x86_64-linux-gnu-cxx03.tar.gz"
[[PPL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f2662cbb8a75e1b8f1d05e87781a8ca83702f5ed"
libc = "glibc"
os = "linux"

    [[PPL.download]]
    sha256 = "c3d7f067677903ff4e976e2aab72ac0756f629f097c1f3b7205dc73f477b3d11"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.0+1/PPL.v1.2.0.x86_64-linux-gnu-cxx11.tar.gz"
[[PPL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ef6d3523d23f689404efb0dade1abbf1f448f066"
libc = "musl"
os = "linux"

    [[PPL.download]]
    sha256 = "f00dd0ee618b63a3d2a631444efd483c16388677f02a5828eba6a3dd7ddaf2b0"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.0+1/PPL.v1.2.0.x86_64-linux-musl-cxx03.tar.gz"
[[PPL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0479600206d3d0c3816fbfa3b66ef0951c6244cb"
libc = "musl"
os = "linux"

    [[PPL.download]]
    sha256 = "3e24082ebd27dfb7a9b0232436210058a39479aa627c904bd3d8d5d2d1c03b83"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.0+1/PPL.v1.2.0.x86_64-linux-musl-cxx11.tar.gz"
[[PPL]]
arch = "x86_64"
git-tree-sha1 = "5332fc0b5757acb4d93172e2cac79105b10e59c9"
os = "freebsd"

    [[PPL.download]]
    sha256 = "c4c4cc89431e969f82825fcfd92dfdc7b333811a94fb53efecd853d8b8bf441f"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.0+1/PPL.v1.2.0.x86_64-unknown-freebsd.tar.gz"
[[PPL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2071bbcd72277b8a2c42c93380d6b57ad90ad549"
os = "windows"

    [[PPL.download]]
    sha256 = "5a7d3da478b7c50f62d2ee05c5a3d7b52fe898a1cc8f243c2c8bd2b2a4c7425e"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.0+1/PPL.v1.2.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[PPL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5180a103c60f1dbb40e68d31ef4ec85cdc256f76"
os = "windows"

    [[PPL.download]]
    sha256 = "b3ac5c7ca255eaeb86af44903137a63bb048d22d4920f47fd37f96ae7c908d22"
    url = "https://github.com/JuliaBinaryWrappers/PPL_jll.jl/releases/download/PPL-v1.2.0+1/PPL.v1.2.0.x86_64-w64-mingw32-cxx11.tar.gz"
