# Autogenerated wrapper script for PPL_jll for aarch64-apple-darwin
export libppl, libppl_c, ppl_config, ppl_lcdd, ppl_pips

using GMP_jll
JLLWrappers.@generate_wrapper_header("PPL")
JLLWrappers.@declare_library_product(libppl, "@rpath/libppl.14.dylib")
JLLWrappers.@declare_library_product(libppl_c, "@rpath/libppl_c.4.dylib")
JLLWrappers.@declare_executable_product(ppl_config)
JLLWrappers.@declare_executable_product(ppl_lcdd)
JLLWrappers.@declare_executable_product(ppl_pips)
function __init__()
    JLLWrappers.@generate_init_header(GMP_jll)
    JLLWrappers.@init_library_product(
        libppl,
        "lib/libppl.14.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libppl_c,
        "lib/libppl_c.4.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        ppl_config,
        "bin/ppl-config",
    )

    JLLWrappers.@init_executable_product(
        ppl_lcdd,
        "bin/ppl_lcdd",
    )

    JLLWrappers.@init_executable_product(
        ppl_pips,
        "bin/ppl_pips",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
